services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: moscow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/moscow
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: dev
      SECURITY_JWT_SECRET_KEY: 131ae5c75439028c8c5d716c65a6b345f0c60291f344641b06591b0fa143d1fb
      SECURITY_JWT_EXPIRATION_TIME: 3600000
      IMGUR_CLIENT_ID: 833612cc84cfd2f
    ports:
      - "8080:8080"

volumes:
  db_data:
